### ISSUE TITLE
consistency of instruction in testing code and structure folder

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [DirtyHarryLYL/HAKE-Action#10]
After retrain model with HICO_DET, i want to test with 
```
python tools/Test_pasta_HICO_DET.py --num_iteration 2000000 --model pasta_HICO-DET
```
First, I get 
```
(act_reg) ubuntu@02203cbabcdc:~/project/Action_Recognition/HAKE-Action$ python tools/Test_pasta_HICO_DET.py --num_iteration 2000000 --model pasta_HICO-DET
Traceback (most recent call last):
  File "tools/Test_pasta_HICO_DET.py", line 15, in <module>
    from models.test_Solver_HICO_DET_pasta import test_net
  File "/home/ubuntu/project/Action_Recognition/HAKE-Action/tools/../lib/models/test_Solver_HICO_DET_pasta.py", line 8, in <module>
    from ult.ult import Get_next_sp_with_pose, Generate_part_bbox, Generate_relation_bbox, Generate_action_object
ModuleNotFoundError: No module named 'ult.ult'
```
I suppose that because you might change file name, so I update from
```
from ult.ult import Get_next_sp_with_pose, Generate_part_bbox, Generate_relation_bbox, Generate_action_object
``` 
in ```/lib/models/test_Solver_HICO_DET_pasta.py", line 8```
to 
```
from ult.ult_HICO_DET  import Get_next_sp_with_pose, Generate_part_bbox, Generate_relation_bbox, Generate_action_object
```

I copy file from `-Result` folder to `lib/util` folder, change
```from ult.ult_HICO_DET import obj_range, get_map``` to 
```from ult.HICO_DET_utils import obj_range, get_map```

so please update your source code to help other.
Please don't name folder start with special character '-Result', it makes me very hard to use with Linux console. 
Tks.

**Comment by NguyenVanThanhHust** [comment]
Beside, you should keep consistency between Readme.MD and source code. 
If you instruct to test with 
```
python tools/Test_pasta_HICO_DET.py --num_iteration 2000000 --model pasta_HICO-DET
``` 
, you shouldn't give helper comment in function is 
```
usage: Test_pasta_HICO_DET.py [-h] [--iteration ITERATION] [--model MODEL]
```
```
Test_pasta_HICO_DET.py: error: unrecognized arguments: --num_iteration 2000000
```

I mean num_iteration vs iteration

**Comment by Foruck** [comment]
Thanks for pointing out! The bugs have been fixed.
And for '-Results', try using './-Results' in Linux console.
