### ISSUE TITLE
ImportError: No module named select_layer

### ISSUE THREAD

**Issue by gyou2019** [DirtyHarryLYL/HAKE-Action#13]
When I ran python scripts/test.py --pasta-mode linear, it showed 

I0527 10:09:12.358407   344 layer_factory.hpp:77] Creating layer select_pairs
ImportError: No module named select_layer
Traceback (most recent call last):
  File "scripts/test.py", line 41, in <module>
    test_one_caffemodel('models/Language-Models/deploy_language-model.prototxt', 'snaps/language_model.caffemodel.h5', 'results/language-model/', 'pvp', 'language-model')
  File "/opt/HAKE-Action/scripts/test_before_mil.py", line 28, in test_one_caffemodel
    caffe.TEST)     # use test mode (e.g., don't perform dropoutet_mode_cpu()
SystemError: NULL result without error in PyObject_Call.

I found deploy_language-model.prototxt called the module named select_layer.
Would you please check it? Thank you.

**Comment by liangxuy** [comment]
Sorry for the missing file. We add select_layer.py under ```python``` folder, please rebuild pycaffe to fix the problem.

**Comment by DirtyHarryLYL** [comment]
Fixed
