### ISSUE TITLE
Image-level分支scripts/test.py文件有几处笔误

### ISSUE THREAD

**Issue by waoup** [DirtyHarryLYL/HAKE-Action#14]
第6行'from obj_mas import prior_info'中的'obj_mask'少写了'k';
第37行'snaps/10v-attention.caffemodel.h5'中的间隔符'-'需要改成'_'，下载的模型名称中用的就是'_'；
第42行和37行一样'snaps/language-model.caffemodel.h5'中的间隔符'-'需要改成'_'；
第47、50、53、56、59行中的'args.mode'需改为'args.pasta_mode'；

我在提供的docker版本上进行了测试，暂时没有出现其他问题。再次感谢作者的工作！

**Comment by liangxuy** [comment]
We have updated the scripts/test.py in this repository and the docker environment. Thanks a lot for your suggestions!

**Comment by waoup** [comment]
作者您好，还有些问题希望您能给予指导。
在test_before_mil.py中，模型的human_roi等输入只能是3x5的吗？这里的3x5是指3个人吗？在使用PaSta-Linear之类的模型时获取的输出为什么不是对应每个人的身体部位状态？

**Comment by liangxuy** [comment]
Image-level-HAKE-Action这个branch的代码适用于图像级别的HOI检测，即给定一张图片，输出该图片中存在的HOI类别。我们沿用了**Pairwise Body-Part Attention for Recognizing Human-Object Interactions**这篇文章的设定，每幅图片选取3个人4个物体，所以human_roi维度为3x5代表3个人，同理object_roi代表4个物体，rel_roi代表3x4=12种组合，scene_roi是全图，part_roi表示3x10个人体部位。
针对第二个问题，由于这份代码适用于图像级别的HOI检测，所以类比于将3个人的HOI结果通过MIL方式合并为全图的检测结果，我们将3个人的各个人体部位状态通过MIL的方式合并成全图的结果。代码参见train_xxx.prototxt里面的MIL操作。

**Comment by DirtyHarryLYL** [comment]
fixed
