### ISSUE TITLE
Where is the defination of global 'model'?. BTW, where is ':' at the end line of def?

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#16]
`def test_one_caffemodel(deploy_file, caffemodel, res_dir, mode, res_name)

    if not os.path.exists(res_dir):
        if mode == 'pvp' or model == '10v':
            os.makedirs(res_dir)   `

**Comment by liangxuy** [comment]
@XXSL980102 Sorry for the typo, it should be ```mode == '10v'```. We will fix the typos in this repository and the docker environment. Thanks a lot!

**Comment by Shunli-Wang** [comment]
Thanks for your replay. I'm very appreciate your work. Very inspiring!
