### ISSUE TITLE
'Instance-level-HAKE-Action' Could you please provide the version of Python in this project?

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#18]
'Instance-level-HAKE-Action' Could you please provide the version of Python in this project?
I used 3.7 but when I pip install all requirements, it showed that some packages are only availible in Py2.7.
Thanks a lot!

**Comment by DirtyHarryLYL** [comment]
We adopt the 2.7.3 in this project:
https://github.com/DirtyHarryLYL/HAKE-Action/blob/e74edace34c18e76f260170d56dd859166f61d0e/requirements.txt#L95
you could try anaconda for convenience.

**Comment by Shunli-Wang** [comment]
Thank you very much!
