### ISSUE TITLE
where is key_mapping?

### ISSUE THREAD

**Issue by xxxzhi** [DirtyHarryLYL/HAKE-Action#20]
Hi, where is key_mapping.pkl in Generate_detection.py? Besides, would u mind provide all 'TIN/xxx.pkl' example files?

**Comment by xxxzhi** [comment]
and hico_caffe600.h5

**Comment by Foruck** [comment]
You could run the following code, and extract the files from the downloaded `tar.gz` file. 
https://github.com/DirtyHarryLYL/HAKE-Action/blob/e74edace34c18e76f260170d56dd859166f61d0e/script/Download_dataset.sh#L22
