### ISSUE TITLE
Demo code?

### ISSUE THREAD

**Issue by anon112233** [DirtyHarryLYL/HAKE-Action#21]
I am wondering if y'all are making a demo for instance-level HAKE-Action which includes Pose detection and the TIN network so that it is easy to test on custom images and other datasets?

**Comment by DirtyHarryLYL** [comment]
Thanks for your nice advice! 
In fact, we are planning to rebuild the pipeline and change it to the PyTorch framework. Thus, it may contain the corresponding object detector and pose estimator.
But we still need some time to complete this, which is also related to some new modules and data under the review.

**Comment by anon112233** [comment]
Thanks for the quick reply! I think this addition would make a big difference in getting others to adopt your superior methodology. Do you know when you plan on completing this work?

**Comment by DirtyHarryLYL** [comment]
The review and rebuilding may cost months. But once the new version is ready, we will release it ASAP in this repo. 
Thanks for your support!
