### ISSUE TITLE
The mismatch of parameters.

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#22]
In **line 372** of **pasta_HICO_DET.py**, the **self.vec_attention** function is called. And the parameters of this function cotains from **fc7_P0** to **fc7_P5**.

`fc7_P_att = self.vec_attention(self.predictions['cls_prob_vec'], fc7_P0, fc7_P1, fc7_P2, fc7_P3, fc7_P4, fc7_P5, fc5_O, initializer, is_training, name='vec_attention')`

But in the defination of **self.vec_attention**, the parametera are fc5_P0 to fc5_P5. Although there is no error, but it's a good choise to fix it up.

`    def vec_attention(self, cls_prob_vec, fc5_P0, fc5_P1, fc5_P2, fc5_P3, fc5_P4, fc5_P5, fc5_O, initializer, is_training, name):
        with tf.variable_scope(name) as scope:
                []
        return fc7_P_att`

**Comment by Foruck** [comment]
Thanks for pointing out! We have fixed it in the latest commit.

**Comment by Shunli-Wang** [comment]
Thanks！

**Comment by Shunli-Wang** [comment]
BTW, in training process have you ever tried to adopt some parallel strategies?
I found that 2,000,000 iters take too much time in single GPU device.
Thanks a lot!

**Comment by DirtyHarryLYL** [comment]
The current version in TF cannot support multi-GPU training. But we are working on the new pytorch version now with a parallel strategy. 
Thanks for your support!
