### ISSUE TITLE
HAKE-Large+iCAN?

### ISSUE THREAD

**Issue by anon112233** [DirtyHarryLYL/HAKE-Action#23]
Your repo is set up to use TIN results but there are results from iCAN+HAKE-Large. If one wants to replicate your iCAN+HAKE-Large results to generate PaSta (like reported in your VCOCO results), what are the steps they should take? Specifically, in Generate_detection.py, a lot seems to be dependent on TIN specific results.

**Comment by Foruck** [comment]
To combine our HAKE-large with other instance-level HOI detection methods (like iCAN), there are two circumstances:
1. You are using the same object detection results as TIN and HAKE-large. For this, replace the score files as shown in the following code with corresponding result files.
https://github.com/DirtyHarryLYL/HAKE-Action/blob/ddce2363023a9187de3fbad77e585abea6106820/-Results/Generate_detection.py#L28-L30
And if necessary, feel free to replace the scale factors and weights in the following code to fit the customized result.
https://github.com/DirtyHarryLYL/HAKE-Action/blob/ddce2363023a9187de3fbad77e585abea6106820/-Results/Generate_detection.py#L42
And corresponding changes might be made to the following code.
https://github.com/DirtyHarryLYL/HAKE-Action/blob/ddce2363023a9187de3fbad77e585abea6106820/-Results/Generate_detection.py#L63-L78

2. You are using different object detection result from TIN and HAKE-large. Besides replacing the score files, the other files also needs re-generation. Note that `pos.pkl` and `neg.pkl` are the interactiveness prediction results from TIN model.
https://github.com/DirtyHarryLYL/HAKE-Action/blob/ddce2363023a9187de3fbad77e585abea6106820/-Results/Generate_detection.py#L28-L40
If necessary, the scale factors, weights and code could also be changed following the above description.

And we will consider making our iCAN+HAKE-Large result public, while for better performance, TIN+HAKE-Large is still preferred.

**Comment by anon112233** [comment]
Thank you for the thorough response. As for making the iCAN+HAKE-Large code public, I think this would be a nice addition for people who want to tradeoff low complexity and low compute for some performance.

**Comment by Foruck** [comment]
Thanks for your advice! We will work on it.
