### ISSUE TITLE
Generating body part boxes from pose joints 

### ISSUE THREAD

**Issue by SupreethN** [DirtyHarryLYL/HAKE-Action#24]
First of all, thanks for open sourcing this fantastic work.

I was reading the paper ```PaStaNet: Toward Human Activity Knowledge Engine``` and I found that you generate body part boxes by first detecting joints using pose methods, and then use some heuristics/ rules to generate bounding boxes. 
I am curious to learn more about the exact rules/ heuristics that you have used.
Would it be possible to find the code used to generate such bounding boxes from joint locations?

**Comment by Foruck** [comment]
Thanks for using our code!
You could find te code for part bounding box generation in [script/part_box_generation.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py).

**Comment by SupreethN** [comment]
Thank you for the swift reply!

Just curious, which code-base/ method was used to generate joints from human pose?

**Comment by Foruck** [comment]
We used [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) to perform the multi-person pose estimation.

**Comment by SupreethN** [comment]
Thanks.
