### ISSUE TITLE
Format for Test_all_part.pkl?

### ISSUE THREAD

**Issue by anon112233** [DirtyHarryLYL/HAKE-Action#25]
Hello again. Is there a specification for the format of the input detection file (for example, Test_all_part.pkl)? I looked through it but do not know the significance of some of the numbers. For context, I'm trying to test this method on my own images and have run iCAN and TIN (with satisfying results), but hope to move on to PaSta detection now.

**Comment by Foruck** [comment]
Thanks for using!
The format of the input detection file is:
```Python
{
    1: [# image_id
            [
                1, # image_id
                [x1, y1, x2, y2], # bounding box
                xx, # object category, 1-80, 1 for human
                xx, # object detection confidence, 0-1
                xx, # useless for PaStaNet
                xx, # useless for PastaNet
                xx, # part bounding box, numpy array with shape of (10, 5) for human and None for object
            ], # an human/object instance
            [1, ...], 
            ...
     ],
     2: [...], 
     ...
}
```
The part bounding box could be generated with [script/part_box_generation.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py).

**Comment by anon112233** [comment]
Great! Thanks

**Comment by AidanAbd** [comment]
One question I have is: what is the meaning of the tuple (x, y) after the part bounding box? This tuple is the last thing in each of the sublists.
