### ISSUE TITLE
Where is the file : ult.HICO_DET_utils

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#27]
in **lib/models/test_Solver_HICO_DET_pasta.py** line 9: 
`from ult.HICO_DET_utils import obj_range, get_map`

There is no such a file named **HICO_DET_utils**.

**Comment by Foruck** [comment]
It is the same file as [-Results/HICO_DET_utils.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/-Results/HICO_DET_utils.py). The following code could create a softlink to solve the path issue. 
https://github.com/DirtyHarryLYL/HAKE-Action/blob/534b225aeaf014e90729e3103dd82142a621176d/script/Download_dataset.sh#L25

**Comment by Shunli-Wang** [comment]
Thank you very much! 
I downloaded all datasets and files in Google Drive manually, so that I missed the last **ln** command in .sh file.
