### ISSUE TITLE
TIN scores format?

### ISSUE THREAD

**Issue by anon112233** [DirtyHarryLYL/HAKE-Action#28]
I have been able to run PaStaNet to generate bboxes, hdet, keys, odet, scores_A, scores_L, and scores_P on custom images, but in the Generate_detection.py file there are a bunch of TIN scores used to generate the detections:

score_H  = pickle.load(open('TIN/score_H.pkl', 'rb')) 
score_O  = pickle.load(open('TIN/score_O.pkl', 'rb')) 
score_sp = pickle.load(open('TIN/score_sp.pkl', 'rb')) 
hdet     = pickle.load(open('TIN/hdet.pkl', 'rb')) 
odet     = pickle.load(open('TIN/odet.pkl', 'rb')) 
keys     = pickle.load(open('TIN/keys.pkl', 'rb')) 
pos      = pickle.load(open('TIN/pos.pkl', 'rb')) 
neg      = pickle.load(open('TIN/neg.pkl', 'rb')) 
bboxes   = pickle.load(open('TIN/bboxes.pkl', 'rb'))

There is also a score_I pulled from the hico_caffe600.h5 file, a key_mapping.pkl, and the generation args file. 

I am hoping y'all can release a description of how to generate these files / the formatting, or release the code used to generate these from TIN results / any other necessary sources. I already have TIN running but am unsure of how to format the results for Generate_detection.py. Thank you!

**Comment by Foruck** [comment]
You could use [this file](https://github.com/DirtyHarryLYL/HAKE-Action/files/4970403/test_HICO_pose_new.zip) to generate the required files, by replacing the original `test_HICO_pose_pattern_all_wise_pair.py` from TIN with `test_HICO_pose_new.py`. Some modifications might need to be done to fit your customized dataset.

**Comment by anon112233** [comment]
Thanks, I'll give it a try tomorrow

**Comment by anon112233** [comment]
What is the role of the obj_range list? Does it just make storing the results in a single array easier or is there more meaning which I am missing?

**Comment by anon112233** [comment]
And as a follow-up, what is the role of hico_caffe600.h5?

**Comment by Foruck** [comment]
`obj_range` mainly helps to re-organize the data into a more compatible format with our re-implemented benchmark.

And for `hico_caffe600.h5`, you could refer to #15 for detailed information.
