### ISSUE TITLE
What is the function of ```Trainval_Neg_all_part.pkl``` ？

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#29]
I can understand that ```Trainval_GT_all_part.pkl``` provides a lot of info which is useful during training, but what is the function of ```Trainval_Neg_all_part.pkl```? I debuged data loading process and found that sometimes one record is provided, sometimes 60 records are provided. I still can't figure it out. Look forward to your reply.

BTW, I can't find the source link to  ```Trainval_GT_10w.pkl```.Can you tell me where to download it? Thank you very much.

```
    num_pos = Pos_augment
    if image_id in Trainval_Neg.keys():
        NEG = Trainval_Neg[image_id]
        if len(NEG) < Neg_select:
            List = range(len(NEG))
        else:
            List = random.sample(range(len(NEG)), Neg_select)
        for i in range(len(List)):
            Neg = NEG[List[i]]
            Human_augmented.append(np.array([0, Neg[2][0], Neg[2][1], Neg[2][2], Neg[2][3]]).reshape(1, 5))
            Object_augmented.append(np.array([0, Neg[3][0], Neg[3][1], Neg[3][2], Neg[3][3]]).reshape(1, 5))
            Relation_augmented.append(Generate_relation_bbox(Neg[2], Neg[3]))
            part_bbox.append(Neg[7][None, :, :])
```

**Comment by Foruck** [comment]
`Trainval_Neg_all_part.pkl` provides additional negative samples to encourage the model to distinguish the differences between the human-object pairs with interaction and without interaction. You could refer to [this link](https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/issues/30) for how the negative samples are generated. Thus, there might be different number of negative samples for different images.

And we will upload `Trainval_GT_10w.pkl` and update the download links ASAP.

**Comment by Shunli-Wang** [comment]
Thank you very much for your reply!

**Comment by Foruck** [comment]
The files have been uploaded, and you could refer to https://github.com/DirtyHarryLYL/HAKE-Action/blob/9bbc87f2b16de12943bc852695194d184757daca/script/Download_dataset.sh#L27-L28 to download them.
