### ISSUE TITLE
请问可以把谷歌云盘的东西上传一份到百度网盘吗？谢谢

### ISSUE THREAD

**Issue by geek12138** [DirtyHarryLYL/HAKE-Action#36]

**Comment by DirtyHarryLYL** [comment]
Thanks, we will consider this, but all the data and models take lots of space and it may take a lot of time.

**Comment by geek12138** [comment]
主要是这玩意
2.3. Download the pretrained model from the Model Zoo and put the models to snaps folder.

python scripts/Download_data.py 1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8 snaps/pretrain_model.caffemodel
在这只能通过这个代码下载，但是不管是正常网络还是vpn都无法下载
谢谢

**Comment by Foruck** [comment]
You could download this file from [https://drive.google.com/file/d/1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8/view](https://drive.google.com/file/d/1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8/view). For other files, you could simply replace the document id (the string between `https://drive.google.com/file/d/` and `/view`) with the first argument of the corresponding command line (`1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8` in this case.)

**Comment by geek12138** [comment]
太感谢了，搞了一天了，差点弃疗了，谢谢

**Comment by geek12138** [comment]
> You could download this file from https://drive.google.com/file/d/1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8/view. For other files, you could simply replace the document id (the string between `https://drive.google.com/file/d/` and `/view`) with the first argument of the corresponding command line (`1iZIE1rNDTNSaGQZcCTAyz1cJnyc4ycA8` in this case.)

太感谢了，搞了一天了，差点弃疗了，谢谢
