### ISSUE TITLE
你好，在Image-level-HAKE-Action的Evaluate的2.Download the provided result file中，没有说provided result file是哪个，谢谢

### ISSUE THREAD

**Issue by geek12138** [DirtyHarryLYL/HAKE-Action#37]
你好，
在Image-level-HAKE-Action的Evaluate的
2.Download the provided result file中，没有说provided result file是哪个，谢谢

此处估计缺失了代码或者说明

**Comment by liangxuy** [comment]
The result files are provided in [this table](https://github.com/DirtyHarryLYL/HAKE-Action/tree/Image-level-HAKE-Action#our-results-on-hico-dataset), you can download them via the Result\_url. The results are in .csv format.
Thank you for you advice, we will revise the readme!

**Comment by geek12138** [comment]
> The result files are provided in [this table](https://github.com/DirtyHarryLYL/HAKE-Action/tree/Image-level-HAKE-Action#our-results-on-hico-dataset), you can download them via the Result_url. The results are in .csv format.
> Thank you for you advice, we will revise the readme!

感谢您的回复，谢谢

**Comment by DirtyHarryLYL** [comment]
Resolved
