### ISSUE TITLE
No such file or directory: './info/hoi.txt'

### ISSUE THREAD

**Issue by geek12138** [DirtyHarryLYL/HAKE-Action#39]
In Image-level HAKE-Action branch, when I run 'python scripts/train.py --pasta-mode linear' in docker. The Error is No such file or directory: './info/hoi.txt'. But I don't know where to find the hoi.txt file.
Thank you.

Traceback (most recent call last):
  File "/opt/HAKE-Action/python/HOI_data_layer-PaSta-Linear.py", line 99, in forward
    im, human_roi, object_roi, rel_roi, scene_roi, part_roi, label,label_wts,hp_list, hp_list_wts, pvp_ankle2, pvp_ankle2_wts, pvp_knee2, pvp_knee2_wts, pvp_hip, pvp_hip_wts, pvp_hand2, pvp_hand2_wts, pvp_shoulder2, pvp_shoulder2_wts, pvp_head, pvp_head_wts, pvp_wts, verb_list, verb_list_wts, object_list, object_list_wts  = self.batch_loader.load_next_image()
  File "/opt/HAKE-Action/python/HOI_data_layer-PaSta-Linear.py", line 236, in load_next_image
    anns = load_annotation(index, self.pascal_root, self.im_shape)
  File "/opt/HAKE-Action/python/HOI_data_layer-PaSta-Linear.py", line 407, in load_annotation
    verb_no = get_verb_no(i+1)
  File "/opt/HAKE-Action/python/HOI_data_layer-PaSta-Linear.py", line 561, in get_verb_no
    with open('./info/hoi.txt', 'r') as f:
IOError: [Errno 2] No such file or directory: './info/hoi.txt'

**Comment by liangxuy** [comment]
hoi.txt is located under `/opt/HAKE-Action/python/info/hoi.txt`. You may need to change the relative path to run the code.

**Comment by geek12138** [comment]
Thanks for your reply, the file has been successfully found and run.
