### ISSUE TITLE
怎么得到human part box

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#41]
作者你好，我看了一下Image-level-action的代码，目前训练还是测试都是直接用生成好的human box, object box还有human part box，我想问一下有没有代码去生成这样的box呢就是从原图

**Comment by DirtyHarryLYL** [comment]
Our script is here: https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/scripts/part_box_processing.py.
You could first use AlphaPose to process all images and obtain the poses.
Object detection can be finished via any detector, e.g., https://github.com/vt-vl-lab/iCAN#demotest-on-your-own-images.
