### ISSUE TITLE
生成的part box和标注的不一样

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#42]
推算的 算的是头部和肩部，标注是颈部和肘部， 而且推算的还有些错误的地方， 所以到底最后用的哪部分。 推算的代码用的是part_box_processing。

**Comment by liangxuy** [comment]
Part box generation is based on the pose detection results(i.e., use Alphapose to obtain pose results). We design some rules to map pose results to part boxes(i.e., see `output_part_box ` function in part_box_processing.py). Further more, we cut sub\_images to refine the part box results as in function `cut_sub_image_save_pos `.  All the implementations are open-sourced in [https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/scripts/part_box_processing.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/scripts/part_box_processing.py).
Could you please make it more clear on "算的是头部和肩部，标注是颈部和肘部" and the errors. Then we will be glad to solve your problems.

**Comment by liangxuy** [comment]
"Head" and "neck", "shoulder" and "arm" have same meanings and only differ in name.
