### ISSUE TITLE
annotation中的label空格和分号分别什么含义

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#45]
想问一下annotation中的label空格和分号分别什么含义，比如第二张图中的label是 131 139 143; 141 ， 那么 他们一共的label 是131 139 143 和 141嘛 为什么中间有个分号。

**Comment by liangxuy** [comment]
The data is borrowed from "Pairwise Body-Part Attention for Recognizing Human-Object Interactions". Please see [https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/python/HOI_data_layer-PaSta-Linear.py#L391-L402](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/python/HOI_data_layer-PaSta-Linear.py#L391-L402) on how to process the labels. And you can download the original data from [this website](http://www-personal.umich.edu/~ywchao/hico/) to figure out the meanings.
