### ISSUE TITLE
iamge-level中的evaluate用matlab部分中用的测试文件是哪一个

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#46]
iamge-level中的evaluate用matlab部分中用的测试文件是哪一个。我测试得到的最后结果是linear-final.csv或者fused.csv，但是我看了matlab中的代码的标注label格式是1,0,-1，（分别代表什么意思这里我也不懂），但是linear-final.csv或者fused.csv的格式是一个600维的数组，看起来是激活值，并不是1,0，-1这样的格式，那么最后的结果我怎么得到1,0,-1呢

**Comment by liangxuy** [comment]
You should copy the fused.csv to `hico_benchmark/data/test-result.csv` (if `hico_benchmark/data/test-result.csv` already exists, then overwrite it). The matlab code will parse `hico_benchmark/data/test-result.csv` for evaluation. The 600-d array indicates the probability that this image contains certain HOI class.

**Comment by whqwill** [comment]
感谢你，但是我们公司禁止使用matlab。代码我看了一下感觉不是很清晰。你能大致说一下代码思路嘛。为什么会有1,0,-1三种标签。

**Comment by liangxuy** [comment]
You can regard -1 as negative labels. In fact, -1 comes from the labelings of HICO dataset and it will take very little effects for the final results.

**Comment by liangxuy** [comment]
PS: For commercial usage, please email us for an agreement.

**Comment by whqwill** [comment]
but 0 is also negative labels? so what is the diffence between 0 and -1. BTW, I evaluate the testing result, the mAP is round 0.68 which is much higher than paper. I don't know it's the GT-PaStaNet result or PaStaNet result.

**Comment by whqwill** [comment]
It's done. I use octave.
