### ISSUE TITLE
为什么先运行PaSta_linear再运行 10v_attention

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#48]
我的理解是10v_attention是用来计算Part Relevance Predictor和Visual PaSta feature的，而PaSta_linear是用来算PaSta-R，为什么顺序是反过来的。
然后最后的结果为什么是10v_attention、PaSta_linear和language model三个结果的fusion。论文的意思是Visual PaSta feature和Language PaSta进行fusion然后再去做PaSta-R。

**Comment by liangxuy** [comment]
Our paper introduces early-fusion while our open-sourced code adopts late-fusion, which is easier for training (i.e., training each branch separately) and tuning.
