### ISSUE TITLE
并没有用到language part?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#49]
image-level的推理部分并没有用到language part? 因为直接取的mil_cls_score_pvp_all而不是language_600？

**Comment by liangxuy** [comment]
In fact, the language part (language_600) is used in our experiment. The bert features are forwarded to two FCs and classify the HOI categories as [Code here](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/models/Language-Models/train_language-model.prototxt#L2401-L2567). This part is proved to be useful.

**Comment by whqwill** [comment]
Thanks. I see. But you did not use the language_600 in the inference part, right?

**Comment by liangxuy** [comment]
In fact, we use the language_600 in the inference time.

**Comment by whqwill** [comment]
Did my code is different from yours???
In the test.py:

            if args.data == 'hico':
                        if not osp.exists('results/language-model/language-model.csv'):
                                 test_one_caffemodel('models/Language-Models/deploy_language-model.prototxt',  'snaps/language_model.caffemodel.h5', 'results/language-model/', 'pvp', 'language-model')
                                 obj_mask_func('results/language-model/language-model.csv')

it shows the mode is "pvp". So in the test_before_mil.py:

            if mode == 'pvp':
                    output_prob_pvp_all = net.blobs['cls_score_pvp_all'].data #part pair
            elif mode =='10v':
                    output_prob_single =  net.blobs['cls_score_single'].data

it use 'cls_score_pvp_all'. I think here should be 'language_600', maybe something wrong?
