### ISSUE TITLE
 Instance-level HOI Demo lack of file

### ISSUE THREAD

**Issue by caodoanh2001** [DirtyHarryLYL/HAKE-Action#5]
Hi,

I am trying to run command train on HICO-DET
It seems that in your lib folder are lacking of matrix_sentence_76.py file ?

Thanks!!
Doanh Bui

**Comment by Foruck** [comment]
Thanks for pointing this out! We have fixed it, and you could run `python script/Download_data.py 1_ubvIeBVIBT2-M0taN4ytf72B5xx0JR7 lib/ult/matrix_sentence_76.py` to download it.

**Comment by caodoanh2001** [comment]
Thanks for this fixing !!
