### ISSUE TITLE
why only ii == 3 in fused.py?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#50]
fused.py:
    for ii in range(1, len(sys.argv)):
        print sys.argv[ii]
        a1 = np.loadtxt(sys.argv[ii], delimiter = ',', dtype = str,usecols=range(600))
        arr1 = a1.astype(np.float)
        for i in range(arr1.shape[0]):
            for j in range(arr1.shape[1]):
                if ii == 3:
                    global_array[i][j] += arr1[i][j] * 2

why only ii == 3 here? it seems it only uses pairwise.csv result.

**Comment by liangxuy** [comment]
This controls the weights of fusing several streams. `ii == 3` indicates that `results/pairwise.csv` has the weight of 2.

**Comment by whqwill** [comment]
OK. I see. Thanks. But the code did not add other parts (attention, pasta, language). Do you check it? I think maybe you miss it.

**Comment by liangxuy** [comment]
The `fuse.py` already combines these parts together.

**Comment by whqwill** [comment]
But the code fuse.py shows:

        for ii in range(1, len(sys.argv)):
                print sys.argv[ii]
                a1 = np.loadtxt(sys.argv[ii], delimiter = ',', dtype = str,usecols=range(600))
                arr1 = a1.astype(np.float)
                for i in range(arr1.shape[0]):
                        for j in range(arr1.shape[1]):
                                if ii == 3:
                                        global_array[i][j] += arr1[i][j] * 2

It did not add the those parts.
