### ISSUE TITLE
language model中 partpairs 的逻辑是什么

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#51]
language model中 partpairs 一共三十对，这里的逻辑是什么。谁和谁应该组合？论文里面没有提到这一点。

**Comment by liangxuy** [comment]
Please see the [codes](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/models/Language-Models/train_language-model.prototxt#L910-L1309) to determine the combined pairs. The way of part pairing is adopted from our previous [work](https://openaccess.thecvf.com/content_ECCV_2018/papers/Haoshu_Fang_Pairwise_Body-Part_Attention_ECCV_2018_paper.pdf).

**Comment by whqwill** [comment]
OK. Thanks.
