### ISSUE TITLE
question about processing methods of ava dataset

### ISSUE THREAD

**Issue by GoodMan0** [DirtyHarryLYL/HAKE-Action#52]
Thanks your great work, could you please release the pre-processing tools/methods of ava dataset, like how to get the human, object, part box and LFB baseline models. The total process is helpful in understanding your work. Thanks again.

**Comment by Foruck** [comment]
Thanks for using!
For the human box and LFB baseline models, please refer to https://github.com/facebookresearch/video-long-term-feature-banks, we directly adopt the human box used by LFB.
AVA dataset doesn't involve object, and we use the whole image box as object box.
For part box, we first run [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose), then generate part box with [part_box_generation.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py).
