### ISSUE TITLE
Maybe can be with the help of external knowledge base

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#54]
hi, I check the paper carefully. I found that this work only uses the language feature of part action. And the reasoning part is just using some combination methods to combine these language feature and visual feature. I have some idea that if we know each part's action (maybe representation can be each part's description), with the help of external knowledge base like wikipedia to reason out the final action. And this is just my idea. BTW, did you think about this ?

**Comment by liangxuy** [comment]
We decompose the HOI detection task into two parts, i.e., obtaining part's action first and then reasoning out the human's action. It seems that your idea belongs to the latter. You can take our part's action labels as input and focus on the reasoning part using the external knowledge base to verify your ideas. We welcome and happy to communicate.

**Comment by whqwill** [comment]
Thanks. I will figure out how to do it.
