### ISSUE TITLE
How to get the "Test_all_part.pkl" in instance-level?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#55]
How to get the "Test_all_part.pkl" in instance-level?

**Comment by Foruck** [comment]
You could download it by https://github.com/DirtyHarryLYL/HAKE-Action/blob/5d762930711faaeb29ce2ca15dfe704dc524fd7e/script/Download_dataset.sh#L16

**Comment by whqwill** [comment]
I mean how to generate it. If I do inference on my own dataset.

**Comment by Foruck** [comment]
For inference on customized dataset, you could first use an object detector to detect the existing human/object instances. Then, AlphaPose is used to detect 2D human pose. Finally, [this script](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py) could be used to generate the pickle file.

**Comment by whqwill** [comment]
Thanks a lot
