### ISSUE TITLE
what's the meaning of hthresh and othresh in the Generate_detection.py

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#59]
what's the meaning of hthresh and othresh in the Generate_detection.py in instance level

**Comment by whqwill** [comment]
BTW, where is the generation_args.pkl from?

**Comment by Foruck** [comment]
1. It means the human and object instances with detection confidence lower hthresh and othresh are ignored in inference and evaluation.
2. They are obtained via grid search on selected validation set from HAKE. You could take reference from https://github.com/DirtyHarryLYL/HAKE-Action/issues/30#issuecomment-678734492.

**Comment by whqwill** [comment]
> 1. It means the human and object instances with detection confidence lower hthresh and othresh are ignored in inference and evaluation.
> 2. They are obtained via grid search on selected validation set from HAKE. You could take reference from [#30 (comment)](https://github.com/DirtyHarryLYL/HAKE-Action/issues/30#issuecomment-678734492).

OK. Thanks. So the hthresh and othresh are also obtained via grid search on selected validation set from HAKE, right?

**Comment by whqwill** [comment]
BTW, if I want to do inference on my own dataset, how should I set hthresh and othresh and other parameters?

**Comment by Foruck** [comment]
For Q1, that's right.
For Q2, maybe a grid search on a selected validation set from your own dataset could do it.
