### ISSUE TITLE
URL issue:

### ISSUE THREAD

**Issue by Juzz4vijay** [DirtyHarryLYL/HAKE-Action#6]
Thank you for your contribution:

I'm using Google Colab environment.

chmod +x ./script/Dataset_download.sh 
./script/Dataset_download.sh

'http://napoli18.eecs.umich.edu/public_html/data/hico_20160224_det.tar.gz'

I can't download dataset from above URL. even, i can't download manually.

**Comment by Foruck** [comment]
Thanks for pointing out! We have updated `./script/Dataset_download.sh` to fix this.
