### ISSUE TITLE
Part Boxes Issue in `Test_all_part.pkl`  file

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#60]
When I run the testing command of HICO-DET in Instance-level-detection, I check the `Test_all_part.pkl` file carefully. I found that all `part boxes` in this file are all the same. There must be something wrong when running the PaStaNet. How does this happen?

Here is the screenshot.:
![image](https://user-images.githubusercontent.com/42674107/98458985-0a529d80-21d1-11eb-9ed6-0648d15b7b2d.png)

**Comment by Foruck** [comment]
This is not a bug. Please notice the previous item, which is a list of length 51. This all-zero list indicates that none of the human key points is detected by AlphaPose. Therefore, the part boxes are all assigned default value: human box.

**Comment by Shunli-Wang** [comment]
Thanks for your replay! In this image, there are two items in the pkl file. I just made a mistake. I correct it right now. And here comes the new question: I visualize all part boxes , but it seems......bad. Is this right?
![image](https://user-images.githubusercontent.com/42674107/98460179-f6ad3400-21dc-11eb-8907-c13f2debdedf.png)

**Comment by Foruck** [comment]
Yes. This is because the pre-defined ratio might be in-flexible. For detailed information, you could take reference from https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py

**Comment by Shunli-Wang** [comment]
Thanks a lot!
