### ISSUE TITLE
how to get the hdet?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#62]
it seems hdet in the test_Solver is from Test_RCNN.pkl. But I check the AlphaPose result, the human score is always bigger than 1.0 , and in the Generation_detection.py it requires hdet < 1.0 .  So maybe I'm wrong, and how to get the hdet? If it is from Object detection (iCAN), how to get the final humans from two different results (AlphaPose and iCAN) ? Thanks.

**Comment by Foruck** [comment]
It is provided by the object detector (Faster-RCNN, which is used by iCAN). For detailed information, you could take reference from https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/part_box_generation.py .
