### ISSUE TITLE
only get 6mAP when using pastanet* only 

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#63]
I only get 6 mAP when I use pastanet only, my code is here (Generation_detection.py):

    # sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
    sHO = (sP + sA + sL) * hod

    for hoi_index in range(x, y):
        #at, bt = athresh[hoi_index], bthresh[hoi_index]
        if hoi_index + 1 in hoi_no_inter_all:
            #nis_mask = 1 - (pos[obj_index] > at) * (neg[obj_index] < bt)
            mask = no_inter_det_mask# * nis_mask
        else:
            #nis_mask = 1 - (pos[obj_index] < at) * (neg[obj_index] > bt)
            mask = inter_det_mask# * nis_mask
        select = np.where(mask > 0)[0]
        detection['scores'][hoi_index] = sHO[select, hoi_index - x]
        detection['bboxes'][hoi_index] = bboxes[obj_index][select]
        detection['keys'][hoi_index] = keys[obj_index][select]

And if I use NIS, the result can be around 20 mAP:

    # sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
    sHO = (sP + sA + sL) * hod

    for hoi_index in range(x, y):
        at, bt = athresh[hoi_index], bthresh[hoi_index]
        if hoi_index + 1 in hoi_no_inter_all:
            nis_mask = 1 - (pos[obj_index] > at) * (neg[obj_index] < bt)
            mask = no_inter_det_mask * nis_mask
        else:
            nis_mask = 1 - (pos[obj_index] < at) * (neg[obj_index] > bt)
            mask = inter_det_mask * nis_mask
        select = np.where(mask > 0)[0]
        detection['scores'][hoi_index] = sHO[select, hoi_index - x]
        detection['bboxes'][hoi_index] = bboxes[obj_index][select]
        detection['keys'][hoi_index] = keys[obj_index][select]

Do I misunderstand something?

**Comment by Foruck** [comment]
Could you provide more detailed information? Like the command line used and the final map.

**Comment by whqwill** [comment]
I got the result like this, and only change the code of calculating sHO: 
a)	TIN+image level+instance level 22.12 mAP : sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
b)	TIN+image level ~21mAP : sHO = (((sH + sO) * ssp) * score_I[im_index[keys[obj_index]], x:y]) * hod
c)	TIN only ~20 mAP : sHO = ((sH + sO) * ssp) * hod
d)	image level+instance level ~14 mAP : sHO = ((sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
e)	instance level only ~6 mAP :  (sP + sA + sL) * hod

Maybe something I understand wrong???

**Comment by Foruck** [comment]
Duplicate with #66.
