### ISSUE TITLE
TIN+PaStaNet*-Linear 的实验结果，需要TIN和PaSta的联合训练吗？

### ISSUE THREAD

**Issue by Shunli-Wang** [DirtyHarryLYL/HAKE-Action#66]
这个工程主要是在对A2V网络进行预训练和微调。而在`Generate_detection.py`文件中直接引入了TIN的检测结果，并且通过
`sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod`
这条语句融合TIN和A2V的结果。针对此我有三点疑惑：

**1：** 这样做需要TIN和A2V Net的联合训练吗？还是分别独立训练之后，直接在这里进行score的融合就可以了？

**2：** 我将sHO融合式子中的sP + sA + sL去掉之后（只用TIN检测结果），发现在HICO上的性能依然很好，和TIN+PaStaNet的效果只差1两个百分点。这是不是说明A2V Net并没有为检测结果提供很大的贡献呢？
`('Default: ', 0.22116964775393347)`
`('Default rare: ', 0.20193286258301021)`
`('Default non-rare: ', 0.22691570046732615)`
`('Known object: ', 0.24059134635026103)`
`('Known object, rare: ', 0.2219354706179083)`
`('Known object, non-rare: ', 0.24616388065992487)`

**3：**`Generate_detection.py`文件中，对`score_P,score_A,score_L`都先除以各自的fac，再通过sigmoid函数转化为概率。`score_P,score_A,score_L`这两个在A2V中取出的时候已经是概率了，除以fac的意义是什么？为什么要再次通过Sigmoid函数？
`score_P[obj_index][:, hoi_index - x]  /= P_fac[hoi_index]`
`score_A[obj_index][:, hoi_index - x]  /= A_fac[hoi_index]`
`score_L[obj_index][:, hoi_index - x]  /= L_fac[hoi_index]`

`sP = torch.sigmoid(torch.from_numpy(score_P[obj_index])).cpu().numpy() * P_weight`
`sA = torch.sigmoid(torch.from_numpy(score_A[obj_index])).cpu().numpy() * A_weight`
`sL = torch.sigmoid(torch.from_numpy(score_L[obj_index])).cpu().numpy() * L_weight`

期待您的回复！

**Comment by whqwill** [comment]
第三个问题和我想问的一样。第二个问题我把TIN的结果去掉后就变得很低了。感觉是不是activity2vec没有训练好。

**Comment by Shunli-Wang** [comment]
嗯嗯，所以这样来看，检测结果大头的贡献还是在TIN。
但是还有一个很神奇的问题，TIN原论文精度大概就17%左右。但是在TIN+PaStaNet这里面，去掉了PaStNet的三个通路信息，单纯TIN的结果可以到20%多。我就很想不通这一点。所以我在问题1里面提问有没有TIN和A2V的联合训练。
![image](https://user-images.githubusercontent.com/42674107/98917772-bcf36a80-2507-11eb-8258-f4b0973366a8.png)

**Comment by whqwill** [comment]
对对对。我测出来和你一样。TIN测出来21%左右。很奇怪，不知道作者用了什么方式。然后你有没有测去掉TIN的情况，我去掉后就只有14%了

**Comment by Shunli-Wang** [comment]
我没有搜到微信....我们加一下QQ? 我的是：3231408683
哈哈哈感觉需要好好交流一下！

**Comment by Foruck** [comment]
You could take reference from #30 and #65 .

**Comment by whqwill** [comment]
I got the result like this, and only change the code of calculating sHO:
a) TIN+image level+instance level 22.12 mAP : sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
b) TIN+image level ~21mAP : sHO = (((sH + sO) * ssp) * score_I[im_index[keys[obj_index]], x:y]) * hod
c) TIN only ~20 mAP : sHO = ((sH + sO) * ssp) * hod
d) image level+instance level ~14 mAP : sHO = ((sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
e) instance level only ~6 mAP : (sP + sA + sL) * hod

Maybe something I understand wrong???

**Comment by Foruck** [comment]
Sorry for the late reply.
Did you use the downloaded detection file or run inference script by yourself?

**Comment by whqwill** [comment]
I used the downloaded detection file, which including pasta_HICO-DET and TIN.

**Comment by DirtyHarryLYL** [comment]
> You could take reference from #30 and #65 .

**Comment by DirtyHarryLYL** [comment]
Duplicated, [https://github.com/DirtyHarryLYL/HAKE-Action/issues/30](#30), [https://github.com/DirtyHarryLYL/HAKE-Action/issues/65](#65)
