### ISSUE TITLE
why use "cls_prob_P" instead of "cls_score_P" in testing?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#67]
I found that in the pasta_HICO_DET.py the test code is as following:

    def test_image_HO(self, sess, image, blobs):
        feed_dict = {self.image: image, 
                     self.H_boxes: blobs['H_boxes'], self.P_boxes: blobs['P_boxes'], self.R_boxes: blobs['R_boxes'], self.O_boxes: blobs['O_boxes'], 
                     self.H_num: blobs['H_num'], self.gt_object: blobs['gt_object'], }
        predictions = sess.run([self.predictions["cls_prob_P"], self.predictions["cls_prob_A"], self.predictions["cls_score_L"]], feed_dict=feed_dict)

        return predictions

why use "cls_prob_P", "cls_prob_A" for P and A, but use "cls_score_L" for L?

**Comment by Foruck** [comment]
Sorry for the late reply.
This is a bug, since all three streams should output 'cls_score'. 
We have fixed it, and the detection file we offered is correct.
