### ISSUE TITLE
language_hoi is not useful?

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#69]
I found that the code in the image-level does not use "language_hoi", so it is useless, right? BTW, I do not find the relative matrix.

**Comment by DirtyHarryLYL** [comment]
No.
Log:
language sole-33.22
PaSta+vanilla MLP--37.87
PaSta+vanilla MLP+language--40.71
laguage+ECCV2018(39)--43.27
PaSta+vanilla MLP+ECCV2018(39)--42.32
PaSta+vanilla MLP+language+ECCV2018(39)--44.00

**Comment by liangxuy** [comment]
`language_hoi` is Silenced and not used. See [here](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Image-level-HAKE-Action/models/Language-Models/train_language-model.prototxt#L740-L744) for your information.

**Comment by DirtyHarryLYL** [comment]
In addition:
The language_hoi is the Bert vector translated directly by the HOI triplets in the beginning.
Later we found that using pvp_55 and obj Bert vectors to compose the HOI vectors would work better: [here](https://github.com/DirtyHarryLYL/HAKE-Action/blob/3cdeed993bef2867ad7f61bcf8c1f2f3994b63a6/models/Language-Models/train_language-model.prototxt#L2373). So we silence language_hoi here and did not use it.

**Comment by whqwill** [comment]
OK. Thanks.
