### ISSUE TITLE
pretrained_models

### ISSUE THREAD

**Issue by Juzz4vijay** [DirtyHarryLYL/HAKE-Action#7]
!python tools/Train_pasta_HICO_DET.py --data <0 for PaStaNet*, 1 for PaStaNet> --init_weight 1 --train_module 2 --num_iteration 2000000 --model <your model name>

Where can i get pre_trained models ckpt.?

can you help me to get pretrained models?

**Comment by DirtyHarryLYL** [comment]
Please use the script to download the pre-trained weights and hico-det dataset: https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/Download_dataset.sh.

Best.

**Comment by DirtyHarryLYL** [comment]
Detialed:
python script/Download_data.py 1ew-uIrD_ZFmO5RFsuMV2sBEqWWVtXkHH Weights/pasta_full.zip
python script/Download_data.py 1h0InSjxCffLuyoXEPbLIzOH0KVWUuUJc Weights/pasta_AVA.zip
python script/Download_data.py 1l12Dr217NeTnbBA5e-9lLetMFmDv7eI9 Weights/pasta_HICO-DET.zip
