### ISSUE TITLE
language分支在train的过程中词向量会不会变

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#71]
看代码的结构，词向量是固定的在python文件中直接读入，那么如果词向量在训练中也变化会不会对最后的结果带来帮助呢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by DirtyHarryLYL** [comment]
In our works, the language vectors are all fixed, e.g., Bert, word2vec, or glove. We also thought about finetuning our model with Bert transformer together, but the training budget and capacity are problems. This sounds interesting, maybe you could have a try on this. 
The thing not sure is whether the joint training would change the semantic meanings of the NLP task-driven language representation. Or you could try to utilize the PaSta labels in pure transformers, i.e., inputting part patches and word labels in multi-modal transformers.

**Comment by whqwill** [comment]
Actually, my meaning is to adjust the vector directly (like the word embedding in the beginning layer in the BERT). But your suggestion is good.

**Comment by DirtyHarryLYL** [comment]
Oh, that's interesting. No idea, we haven't tried this. 
Maybe you could dig this.

**Comment by whqwill** [comment]
OK. Thanks. I will try it.
