### ISSUE TITLE
image level中的GT PaStaNet 中的part state GT是否用于训练了

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#73]
image level中的GT PaStaNet 中数值 是训练PaSta R的时候(主要是language分支) 用的part state的GT还是说只是测试的时候用到了part state的GT. 因为这里我在考虑这个方法的upper bound会是多少.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by DirtyHarryLYL** [comment]
GT Pastanet means: using the final trained model, input the GT pasta labels of the test set to the reasoning R submodel to test the upper bound, i.e., pasta recognizer can perfectly recognize the part states.
In training, pasta labels of the test set are unseen.

**Comment by whqwill** [comment]
OK. Thanks.
