### ISSUE TITLE
针对少样本的类别或许可以用rule based来代替神经网络

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#74]
今天我用rule based的方法针对bicycle的类别做了设计，就人为设计推理部分，如果part state满足一定条件，就分为该类，然后结合part state GT事实证明只要不是特别依赖场景背景的动作(比如 jumb bicycle这个动作主要是考察bicycle是否腾空) 结果都比较好。而且在wash bicycle这个动作上达到了90以上，然而用神经网络训觉的方式wash bicycle结果很差，原因是我观察了训练集只有一个数据而且hand state的标注都没有wash这个动作，所以这个类别不管怎么学都没办法让测试集提高。所以我在考虑针对特别是少量样本的类别或许用这样rule based的方法会更好。

另外，对于jump bicycle这种类别主要是检测物体状态其实就是看bicycle有没有腾空，然后repair bicycle可以通过检测bicycle是否有倒过来或者是局部放大来检测。 然后我还观察了buy 这个动作 冷检测是否在shop或者supermarket 的场景来检测。 这些大概是我的一点思路。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by DirtyHarryLYL** [comment]
Sure, for simple actions, using rules are more robust than the DNN sometimes. But more complex scenes are more difficult for rule design and pasta recognition.
