### ISSUE TITLE
pasta的短语长度很多情况大于3 为什么语言向量只有两个 怎么得到的

### ISSUE THREAD

**Issue by whqwill** [DirtyHarryLYL/HAKE-Action#78]
pasta的短语长度很多情况大于3 为什么语言向量只有两个 怎么得到的 ，比如foot no interaction这里就有三个单词

**Comment by DirtyHarryLYL** [comment]
If the action token is "sit on", we add two 768-sized embeddings of "sit" and "on" to get a 768-sized  embedding.
