### ISSUE TITLE
Temporal action Localization

### ISSUE THREAD

**Issue by xjgnqnl** [DirtyHarryLYL/HAKE-Action#79]
Is it useful on the task : Temporal action Localization?For example,Just like ActivityNet1.3,THUMOS4
which needs identify the action class by trimmed videos？I‘m very interested in this aspect！！！

**Comment by DirtyHarryLYL** [comment]
Sorry for the late response. We are working on the AVA, i.e., action detection from videos (detect humans and classify the performing actions). We plan to release the video code this year. Thanks for your attention.
In the video, human body part states also work as a kind of finer and Spatio-temporal descriptor for the dynamic human body motions.
