### ISSUE TITLE
No Generate_detection.py in Instance-HAKE

### ISSUE THREAD

**Issue by hyzcn** [DirtyHarryLYL/HAKE-Action#83]
Hi, many thanks for sharing the great work! However, I found that there is no "Generate_detection.py" file under Instance-HAKE branch, is it missing?

**Comment by DirtyHarryLYL** [comment]
Please check this file: https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/-Results/Generate_detection.py
