### ISSUE TITLE
HAKE2.0论文中AVA的基于GT human boxes的47.27mAP如何得到的？

### ISSUE THREAD

**Issue by ZZZZZZZZJ** [DirtyHarryLYL/HAKE-Action#85]
![image](https://user-images.githubusercontent.com/19664953/166855364-fdb103a7-8d89-4c6d-a9aa-6491b247122b.png)
在HAKE2.0论文中，表1列出当GT-HAKE在GT H boxes的可以得到mAP为47.27的上限值。请问这个上限值是如何得到的？
我尝试直接使用标注的pasta ava中的标签，进行one-hot编码后，用1~2层的MLP进行训练预测，但是仅能得到40.42的mAP。
这让我有些困惑。

**Comment by DirtyHarryLYL** [comment]
Thanks for your interest in HAKE. 
The GT-HAKE model uses both visual and language primitive features given GT primitive labels and adopts the neural-symbolic reasoning module to get the result. Thus, one-hot label and MLP may not achieve the same effect. 
Our paper is still under review, we will release the code, data, and the pre-trained model when the official version is accepted. Thank you.
